# Generated by Django 5.0.7 on 2024-08-05 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_olympics_delete_sport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="olympics",
            name="id",
        ),
        migrations.AddField(
            model_name="olympics",
            name="category",
            field=models.CharField(default="Null", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="olympics",
            name="sport_id",
            field=models.IntegerField(default="1", primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "sport_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.olympics",
                    ),
                ),
            ],
        ),
    ]
