# Generated by Django 5.0.7 on 2024-08-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_remove_olympics_id_olympics_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="sport_id",
            field=models.IntegerField(),
        ),
    ]
