# Generated by Django 5.0.7 on 2024-08-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_alter_sport_sport_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="image",
            field=models.ImageField(upload_to="media"),
        ),
    ]
