# Generated by Django 5.0.7 on 2024-08-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_alter_sport_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.BinaryField()),
            ],
        ),
    ]
